// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQUgeIJbdZL-WIqkFW_z7DtInttsD_dQo',
    appId: '1:799135902364:web:dad4a40dab4eccde359b59',
    messagingSenderId: '799135902364',
    projectId: 'smart-campus-app-5d7de',
    authDomain: 'smart-campus-app-5d7de.firebaseapp.com',
    storageBucket: 'smart-campus-app-5d7de.firebasestorage.app',
    measurementId: 'G-GC78K0X78R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3O8cH8AkjIjjwWsrFqhWg7nPDmXkinak',
    appId: '1:799135902364:android:7b93ade6e3967e05359b59',
    messagingSenderId: '799135902364',
    projectId: 'smart-campus-app-5d7de',
    storageBucket: 'smart-campus-app-5d7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4aLfPwlfgh8SJDaCH-XDKIOOg_4gstbI',
    appId: '1:799135902364:ios:d5d33d791fd44aa2359b59',
    messagingSenderId: '799135902364',
    projectId: 'smart-campus-app-5d7de',
    storageBucket: 'smart-campus-app-5d7de.firebasestorage.app',
    androidClientId: '799135902364-26pcp1fogmm1ku503scve6srsud2v0tg.apps.googleusercontent.com',
    iosClientId: '799135902364-59fgmdbvt22j0mramo3u09v9ghmnafv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4aLfPwlfgh8SJDaCH-XDKIOOg_4gstbI',
    appId: '1:799135902364:ios:d5d33d791fd44aa2359b59',
    messagingSenderId: '799135902364',
    projectId: 'smart-campus-app-5d7de',
    storageBucket: 'smart-campus-app-5d7de.firebasestorage.app',
    androidClientId: '799135902364-26pcp1fogmm1ku503scve6srsud2v0tg.apps.googleusercontent.com',
    iosClientId: '799135902364-59fgmdbvt22j0mramo3u09v9ghmnafv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsManagement',
  );
}
